import { isAdmin } from "@/lib/admin-auth";
import { DEFAULT_SETTINGS } from "@/config/conference";
import { prisma } from "@/lib/prisma";
import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/field";
import ImageUpload from "@/components/ImageUpload";
import LoginForm from "@/components/LoginForm";
import { createCommittee, createTeamMember, deleteCommittee, deleteTeamMember, login, logout, saveSettings, updateCommittee, updateTeamMember } from "./actions";

export const metadata = { title: "Administration", robots: { index: false, follow: false } };
export const instant = false;

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  const query = await searchParams;
  if (!await isAdmin()) return <div className="site-container grid min-h-[70svh] place-items-center py-16"><LoginForm action={login} error={!!query.error} /></div>;
  const [stored, committees, team] = await Promise.all([prisma.conferenceSettings.findUnique({ where: { id: 1 } }), prisma.committee.findMany({ orderBy: { sortOrder: "asc" } }), prisma.teamMember.findMany({ orderBy: { sortOrder: "asc" } })]);
  const settings = stored?.data || DEFAULT_SETTINGS;
  return <div className="site-container py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-[var(--red)]">BUFALOMUN</p><h1 className="mt-2 font-display text-6xl">Content administration</h1></div><form action={logout}><Button variant="secondary" type="submit">Sign out</Button></form></div>{query.saved && <p className="mt-6 border-l-4 border-green-700 bg-green-50 p-4 text-sm font-bold text-green-800">Changes saved and published.</p>}
    <section className="mt-14 border-t border-[var(--border)] pt-8"><h2 className="font-display text-4xl">Site settings</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">Edit conference details, section visibility, application copy and questions, and letters. Keep the JSON structure intact.</p><form action={saveSettings} className="mt-6"><Textarea name="settings" defaultValue={JSON.stringify(settings, null, 2)} className="min-h-[36rem] font-mono text-xs" spellCheck={false} required />{query.error === "json" && <p className="mt-2 text-sm text-red-700">The settings JSON is invalid.</p>}<Button type="submit" className="mt-4">Publish settings</Button></form></section>
    <div className="mt-16 grid gap-14 lg:grid-cols-2"><section><h2 className="font-display text-4xl">Committees</h2><form action={createCommittee} className="mt-6 grid gap-3 rounded-lg border border-[var(--border)] bg-white p-5"><Input name="name" placeholder="Committee name" required /><ImageUpload /><Textarea name="description" placeholder="Description" required /><label className="flex items-center gap-2 text-sm"><input name="isPublished" type="checkbox" defaultChecked /> Published</label><Button type="submit">Add committee</Button></form><div className="mt-5 space-y-4">{committees.map((item) => <form key={item.id} action={updateCommittee} className="grid gap-3 border border-[var(--border)] bg-white p-4"><input type="hidden" name="id" value={item.id} /><Input name="name" defaultValue={item.name} required /><ImageUpload defaultValue={item.imageUrl || ""} /><Textarea name="description" defaultValue={item.description} required /><label className="flex items-center gap-2 text-sm"><input name="isPublished" type="checkbox" defaultChecked={item.isPublished} /> Published</label><div className="flex gap-2"><Button type="submit">Save</Button><Button type="submit" variant="danger" formAction={deleteCommittee}>Delete</Button></div></form>)}</div></section>
    <section><h2 className="font-display text-4xl">Secretariat</h2><form action={createTeamMember} className="mt-6 grid gap-3 rounded-lg border border-[var(--border)] bg-white p-5"><Input name="name" placeholder="Full name" required /><Input name="role" placeholder="Role" required /><ImageUpload /><Input name="instagram" type="url" placeholder="Instagram URL (optional)" /><Textarea name="bio" placeholder="Biography" required /><label className="flex items-center gap-2 text-sm"><input name="isPublished" type="checkbox" defaultChecked /> Published</label><Button type="submit">Add team member</Button></form><div className="mt-5 space-y-4">{team.map((item) => <form key={item.id} action={updateTeamMember} className="grid gap-3 border border-[var(--border)] bg-white p-4"><input type="hidden" name="id" value={item.id} /><Input name="name" defaultValue={item.name} required /><Input name="role" defaultValue={item.role} required /><ImageUpload defaultValue={item.imageUrl || ""} /><Input name="instagram" type="url" defaultValue={item.instagram || ""} placeholder="Instagram URL" /><Textarea name="bio" defaultValue={item.bio} required /><label className="flex items-center gap-2 text-sm"><input name="isPublished" type="checkbox" defaultChecked={item.isPublished} /> Published</label><div className="flex gap-2"><Button type="submit">Save</Button><Button type="submit" variant="danger" formAction={deleteTeamMember}>Delete</Button></div></form>)}</div></section></div>
  </div>;
}
